// PHRONESIS seed script — populates the database with an elite fleet
// Run with: bun run scripts/seed.ts
import { db } from '../src/lib/db';

async function main() {
  console.log('🌱 Seeding PHRONESIS database...');

  // Idempotent: wipe existing data first
  await db.booking.deleteMany();
  await db.carImage.deleteMany();
  await db.car.deleteMany();
  await db.category.deleteMany();
  await db.brand.deleteMany();
  await db.siteSettings.deleteMany();
  console.log('  ✓ Cleared existing data');

  // ---------- Categories ----------
  const sports    = await db.category.create({ data: { name: 'Sports',    slug: 'sports',    description: 'Track-bred performance machines' } });
  const luxury    = await db.category.create({ data: { name: 'Luxury',    slug: 'luxury',    description: 'Hand-crafted grand tourers' } });
  const suv       = await db.category.create({ data: { name: 'SUV',       slug: 'suv',       description: 'Commanding presence, supreme comfort' } });
  const hyper     = await db.category.create({ data: { name: 'Hypercar',  slug: 'hypercar',  description: 'The absolute pinnacle of automotive engineering' } });
  const convert   = await db.category.create({ data: { name: 'Convertible', slug: 'convertible', description: 'Open-top freedom under the Al Ain sun' } });
  const sedan     = await db.category.create({ data: { name: 'Sedan',     slug: 'sedan',     description: 'Comfortable daily drivers for every journey' } });
  const compact   = await db.category.create({ data: { name: 'Compact',   slug: 'compact',   description: 'Efficient, agile, perfect for city driving' } });

  // ---------- Brands ----------
  const lamborghini = await db.brand.create({ data: { name: 'Lamborghini', slug: 'lamborghini' } });
  const rollsroyce  = await db.brand.create({ data: { name: 'Rolls-Royce', slug: 'rolls-royce' } });
  const bentley     = await db.brand.create({ data: { name: 'Bentley',     slug: 'bentley' } });
  const ferrari     = await db.brand.create({ data: { name: 'Ferrari',     slug: 'ferrari' } });
  const mclaren     = await db.brand.create({ data: { name: 'McLaren',     slug: 'mclaren' } });
  const mercedes    = await db.brand.create({ data: { name: 'Mercedes-Maybach', slug: 'mercedes-maybach' } });
  const rover       = await db.brand.create({ data: { name: 'Range Rover', slug: 'range-rover' } });
  const porsche     = await db.brand.create({ data: { name: 'Porsche',     slug: 'porsche' } });
  const aston       = await db.brand.create({ data: { name: 'Aston Martin', slug: 'aston-martin' } });
  const bmw         = await db.brand.create({ data: { name: 'BMW',         slug: 'bmw' } });
  const audi        = await db.brand.create({ data: { name: 'Audi',        slug: 'audi' } });
  const nissan      = await db.brand.create({ data: { name: 'Nissan',      slug: 'nissan' } });
  const honda       = await db.brand.create({ data: { name: 'Honda',       slug: 'honda' } });
  const toyota      = await db.brand.create({ data: { name: 'Toyota',      slug: 'toyota' } });
  const chevrolet   = await db.brand.create({ data: { name: 'Chevrolet',   slug: 'chevrolet' } });
  const hyundai     = await db.brand.create({ data: { name: 'Hyundai',     slug: 'hyundai' } });
  const mitsubishi  = await db.brand.create({ data: { name: 'Mitsubishi',  slug: 'mitsubishi' } });
  const kia         = await db.brand.create({ data: { name: 'Kia',         slug: 'kia' } });
  const mercedesB   = await db.brand.create({ data: { name: 'Mercedes-Benz', slug: 'mercedes-benz' } });

  // ---------- Cars ----------
  const cars = [
    {
      slug: 'lamborghini-huracan-evo',
      brand: lamborghini,
      model: 'Huracán EVO',
      year: 2024,
      category: sports,
      priceDaily: 2800, priceWeekly: 16800, priceMonthly: 65000,
      engine: '5.2L V10', power: '631 HP', topSpeed: '325 km/h', acceleration: '2.9s (0-100)',
      transmission: '7-speed DCT', seats: 2, fuelType: 'Petrol', drivetrain: 'AWD',
      tagline: 'Naturally aspirated V10 fury, sharpened for the street.',
      description: 'The Huracán EVO is the definitive expression of Lamborghini engineering — a naturally aspirated 5.2-litre V10 paired with rear-wheel steering and LDVI vehicle dynamics. Every input is translated into instant, telepathic response. Available in Al Ain with full insurance, 24/7 delivery, and zero deposit for verified guests.',
      features: ['Naturally Aspirated V10', 'Rear-Wheel Steering', 'LDVI Brain', 'Carbon Ceramic Brakes', 'Apple CarPlay', 'Alcantara Interior'],
      color: 'Arancio Borealis',
      available: true, featured: true,
      mileageLimit: '250 km/day', deposit: 'AED 5,000 refundable',
      heroImage: 'https://images.unsplash.com/photo-1621135802920-133df287f89c?w=1600&q=85',
      images: [
        'https://images.unsplash.com/photo-1621135802920-133df287f89c?w=1600&q=85',
        'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1600&q=85',
        'https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=1600&q=85',
      ],
    },
    {
      slug: 'rolls-royce-ghost',
      brand: rollsroyce,
      model: 'Ghost',
      year: 2024,
      category: luxury,
      priceDaily: 3500, priceWeekly: 21000, priceMonthly: 80000,
      engine: '6.75L V12', power: '563 HP', topSpeed: '250 km/h', acceleration: '4.8s (0-100)',
      transmission: '8-speed ZF', seats: 4, fuelType: 'Petrol', drivetrain: 'AWD',
      tagline: 'Whisper-quiet opulence, engineered around you.',
      description: 'The Ghost distills Rolls-Royce luxury into its purest form — a 6.75-litre V12 with satellite-aided transmission, Planar suspension system, and a cabin insulated to near silence. Hand-stitched leather, real wood veneer, and the Starlight Headliner create a sanctuary on wheels. Delivered to your hotel or residence anywhere in the UAE.',
      features: ['Starlight Headliner', 'Planar Suspension', 'Bespoke Audio', 'Massage Seats', 'Whisper-Quiet Cabin', 'Satellite-Aided Transmission'],
      color: 'Arctic White',
      available: true, featured: true,
      mileageLimit: '300 km/day', deposit: 'AED 7,500 refundable',
      heroImage: 'https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=1600&q=85',
      images: [
        'https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=1600&q=85',
        'https://images.unsplash.com/photo-1614026480209-9bc5b9d6e8d9?w=1600&q=85',
        'https://images.unsplash.com/photo-1583836863538-91e9f97a8d76?w=1600&q=85',
      ],
    },
    {
      slug: 'bentley-continental-gt',
      brand: bentley,
      model: 'Continental GT Speed',
      year: 2024,
      category: luxury,
      priceDaily: 2700, priceWeekly: 16200, priceMonthly: 60000,
      engine: '6.0L W12', power: '650 HP', topSpeed: '335 km/h', acceleration: '3.5s (0-100)',
      transmission: '8-speed DCT', seats: 4, fuelType: 'Petrol', drivetrain: 'AWD',
      tagline: 'The grand tourer, perfected.',
      description: 'The Continental GT Speed blends British craftsmanship with devastating performance. A 6.0-litre W12 sends 650 horsepower to all four wheels, while the rotating Bentley display toggles between elegant walnut veneer, three analogue dials, and a 12.3-inch touchscreen. A grand tourer for those who refuse to compromise.',
      features: ['Rotating Bentley Display', 'Diamond Quilted Leather', 'Naim Audio', 'Air Suspension', 'All-Wheel Steering', 'Carbon Ceramic Brakes'],
      color: 'Glacier White',
      available: true, featured: true,
      mileageLimit: '300 km/day', deposit: 'AED 5,000 refundable',
      heroImage: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=1600&q=85',
      images: [
        'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=1600&q=85',
        'https://images.unsplash.com/photo-1606152421811-aa9143a350e1?w=1600&q=85',
        'https://images.unsplash.com/photo-1612825173281-9a193378527e?w=1600&q=85',
      ],
    },
    {
      slug: 'ferrari-roma',
      brand: ferrari,
      model: 'Roma',
      year: 2024,
      category: sports,
      priceDaily: 3200, priceWeekly: 19200, priceMonthly: 72000,
      engine: '3.9L V8 Turbo', power: '612 HP', topSpeed: '320 km/h', acceleration: '3.4s (0-100)',
      transmission: '8-speed DCT', seats: 4, fuelType: 'Petrol', drivetrain: 'RWD',
      tagline: 'La Nuova Dolce Vita — Roman beauty, Maranello soul.',
      description: 'The Ferrari Roma is a contemporary GT with timeless proportions — a long bonnet, fastback roofline, and a 620-horsepower twin-turbo V8. The cockpit is split into two distinct zones for driver and passenger. Dual-cockpit architecture, full digital interface, and that unmistakable Maranello exhaust note.',
      features: ['Twin-Turbo V8', 'Dual-Cockpit Architecture', 'Side-Slip Control 6.0', 'Burmester Audio', 'Carbon Fibre Steering Wheel', 'Race Mode'],
      color: 'Rosso Corsa',
      available: true, featured: true,
      mileageLimit: '250 km/day', deposit: 'AED 7,500 refundable',
      heroImage: 'https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=1600&q=85',
      images: [
        'https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=1600&q=85',
        'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1600&q=85',
        'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=1600&q=85',
      ],
    },
    {
      slug: 'mclaren-720s',
      brand: mclaren,
      model: '720S Spider',
      year: 2024,
      category: hyper,
      priceDaily: 4500, priceWeekly: 27000, priceMonthly: 100000,
      engine: '4.0L V8 Twin-Turbo', power: '710 HP', topSpeed: '341 km/h', acceleration: '2.9s (0-100)',
      transmission: '7-speed SSG', seats: 2, fuelType: 'Petrol', drivetrain: 'RWD',
      tagline: 'A supercar without compromise — open-top or closed.',
      description: 'The McLaren 720S Spider is built around a carbon fibre MonoCage II-S, delivering hypercar performance with retractable-roof freedom. 710 horsepower, 7,500 rpm redline, and active aerodynamics that shift the car\'s centre of pressure in real time. One of the most rewarding driving experiences money can rent.',
      features: ['Carbon MonoCage II-S', 'Active Aerodynamics', 'ProActive Chassis Control II', 'Retractable Hardtop (11s)', 'Electrochromic Roof', 'Track Telemetry'],
      color: 'Papaya Spark',
      available: true, featured: true,
      mileageLimit: '200 km/day', deposit: 'AED 10,000 refundable',
      heroImage: 'https://images.unsplash.com/photo-1583836863538-91e9f97a8d76?w=1600&q=85',
      images: [
        'https://images.unsplash.com/photo-1583836863538-91e9f97a8d76?w=1600&q=85',
        'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1600&q=85',
        'https://images.unsplash.com/photo-1621135802920-133df287f89c?w=1600&q=85',
      ],
    },
    {
      slug: 'mercedes-maybach-s680',
      brand: mercedes,
      model: 'Maybach S 680 4MATIC',
      year: 2024,
      category: luxury,
      priceDaily: 2400, priceWeekly: 14400, priceMonthly: 55000,
      engine: '6.0L V12 Biturbo', power: '612 HP', topSpeed: '250 km/h', acceleration: '4.5s (0-100)',
      transmission: '9G-Tronic', seats: 4, fuelType: 'Petrol', drivetrain: 'AWD',
      tagline: 'The chauffeured flagship, reimagined.',
      description: 'The Mercedes-Maybach S 680 is the pinnacle of the S-Class lineage — a 6.0-litre V12 biturbo, executive rear seats with massage, heating and ventilation, a Burmester 4D surround system, and the world\'s quietest cabin at speed. Includes a dedicated chauffeur option for Al Ain, Abu Dhabi, and Dubai engagements.',
      features: ['Executive Rear Seats', 'Burmester 4D Audio', 'Magic Body Control', 'Chauffeur Available', 'Rear Refrigerator', 'Manufaktur Nappa Leather'],
      color: 'Obsidian Black',
      available: true, featured: false,
      mileageLimit: '300 km/day', deposit: 'AED 5,000 refundable',
      heroImage: 'https://images.unsplash.com/photo-1612825173281-9a193378527e?w=1600&q=85',
      images: [
        'https://images.unsplash.com/photo-1612825173281-9a193378527e?w=1600&q=85',
        'https://images.unsplash.com/photo-1606152421811-aa9143a350e1?w=1600&q=85',
        'https://images.unsplash.com/photo-1614026480209-9bc5b9d6e8d9?w=1600&q=85',
      ],
    },
    {
      slug: 'range-rover-autobiography',
      brand: rover,
      model: 'Range Rover Autobiography',
      year: 2024,
      category: suv,
      priceDaily: 1900, priceWeekly: 11400, priceMonthly: 45000,
      engine: '4.4L V8 Twin-Turbo', power: '523 HP', topSpeed: '242 km/h', acceleration: '4.6s (0-100)',
      transmission: '8-speed Auto', seats: 5, fuelType: 'Petrol', drivetrain: 'AWD',
      tagline: 'Unrivalled refinement, on road or off.',
      description: 'The Range Rover Autobiography is the most luxurious SUV ever built by Land Rover — a 523-horsepower V8, executive rear seats with 24-way adjustment, Meridian signature sound system, and a silent, calm cabin. Equally at home on Sheikh Zayed Road or a desert retreat.',
      features: ['Executive Class Rear Seats', 'Meridian Signature Audio', 'Cabin Air Purification Pro', 'Air Suspension', 'Terrain Response 2', 'Panoramic Roof'],
      color: 'Santorini Black',
      available: true, featured: false,
      mileageLimit: '300 km/day', deposit: 'AED 4,000 refundable',
      heroImage: 'https://images.unsplash.com/photo-1606152421811-aa9143a350e1?w=1600&q=85',
      images: [
        'https://images.unsplash.com/photo-1606152421811-aa9143a350e1?w=1600&q=85',
        'https://images.unsplash.com/photo-1612825173281-9a193378527e?w=1600&q=85',
        'https://images.unsplash.com/photo-1614026480209-9bc5b9d6e8d9?w=1600&q=85',
      ],
    },
    {
      slug: 'porsche-911-turbo-s',
      brand: porsche,
      model: '911 Turbo S',
      year: 2024,
      category: sports,
      priceDaily: 3000, priceWeekly: 18000, priceMonthly: 68000,
      engine: '3.7L Flat-6 Twin-Turbo', power: '640 HP', topSpeed: '330 km/h', acceleration: '2.7s (0-100)',
      transmission: '8-speed PDK', seats: 4, fuelType: 'Petrol', drivetrain: 'AWD',
      tagline: 'The everyday supercar, perfected.',
      description: 'The 911 Turbo S is the apex of the 911 lineage — 640 horsepower, 800 Nm of torque, launch control, and a 0-100 sprint of just 2.7 seconds. Yet it remains as livable in Tuesday morning traffic as it is devastating on the weekend. The benchmark by which all other sports cars are measured.',
      features: ['640 HP Flat-6', 'Sport Chrono Package', 'PASM Suspension', 'Ceramic Brakes', 'Burmester Audio', 'Launch Control'],
      color: 'GT Silver',
      available: true, featured: true,
      mileageLimit: '250 km/day', deposit: 'AED 6,000 refundable',
      heroImage: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1600&q=85',
      images: [
        'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1600&q=85',
        'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1600&q=85',
        'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1600&q=85',
      ],
    },
    // ===== NEW: 2nd SUV =====
    {
      slug: 'mercedes-g63-amg',
      brand: mercedes,
      model: 'G63 AMG',
      year: 2024,
      category: suv,
      priceDaily: 2200, priceWeekly: 13200, priceMonthly: 52000,
      engine: '4.0L V8 Biturbo', power: '585 HP', topSpeed: '240 km/h', acceleration: '4.5s (0-100)',
      transmission: '9-speed Auto', seats: 5, fuelType: 'Petrol', drivetrain: 'AWD',
      tagline: 'The iconic box — reimagined as a 585-horsepower statement.',
      description: 'The Mercedes-AMG G63 is the definitive luxury off-roader — a hand-built 4.0L V8 biturbo, three locking differentials, and that unmistakable squared-off silhouette. Inside, Nappa leather, dual 12.3-inch displays, and Burmester surround sound create a cockpit unlike anything else on the road. Equally at home carving desert dunes or pulling up to a 5-star hotel.',
      features: ['Hand-Built V8', 'Three Locking Differentials', 'Burmester Surround Sound', 'Nappa Leather Interior', 'Adaptive Damping', 'AMG Performance Exhaust'],
      color: 'Obsidian Black',
      available: true, featured: false,
      mileageLimit: '300 km/day', deposit: 'AED 5,000 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/d112dd39ef58.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/d112dd39ef58.jpg',
        'https://sfile.chatglm.cn/images-ppt/d112dd39ef58.jpg',
        'https://sfile.chatglm.cn/images-ppt/d112dd39ef58.jpg',
      ],
    },
    // ===== NEW: 2nd Hypercar =====
    {
      slug: 'ferrari-sf90-stradale',
      brand: ferrari,
      model: 'SF90 Stradale',
      year: 2024,
      category: hyper,
      priceDaily: 5500, priceWeekly: 33000, priceMonthly: 120000,
      engine: '4.0L V8 + 3 Electric Motors', power: '986 HP', topSpeed: '340 km/h', acceleration: '2.5s (0-100)',
      transmission: '8-speed DCT', seats: 2, fuelType: 'Hybrid', drivetrain: 'AWD',
      tagline: 'Ferrari\'s first series-production plug-in hybrid hypercar.',
      description: 'The SF90 Stradale is a technological watershed — a 4.0L twin-turbo V8 paired with three electric motors producing a combined 986 horsepower. 0-100 in 2.5 seconds. This is the most powerful road-going Ferrari ever built, and the first to feature all-wheel drive in a mid-engine layout. Available for the discerning few who demand the absolute pinnacle.',
      features: ['986 HP Hybrid Powertrain', '3 Electric Motors', 'All-Wheel Drive', 'eManettino Mode Selector', 'Carbon Fibre Monocoque', 'Plug-in Hybrid (25km EV range)'],
      color: 'Rosso Corsa',
      available: true, featured: true,
      mileageLimit: '200 km/day', deposit: 'AED 12,000 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/69d822d14d49.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/69d822d14d49.jpg',
        'https://sfile.chatglm.cn/images-ppt/69d822d14d49.jpg',
        'https://sfile.chatglm.cn/images-ppt/69d822d14d49.jpg',
      ],
    },
    // ===== NEW: 1st Convertible =====
    {
      slug: 'aston-martin-vantage-roadster',
      brand: aston,
      model: 'Vantage Roadster',
      year: 2024,
      category: convert,
      priceDaily: 2800, priceWeekly: 16800, priceMonthly: 65000,
      engine: '4.0L V8 Twin-Turbo', power: '503 HP', topSpeed: '306 km/h', acceleration: '3.7s (0-100)',
      transmission: '8-speed ZF', seats: 2, fuelType: 'Petrol', drivetrain: 'RWD',
      tagline: 'Open-top British theatre, with a German heart.',
      description: 'The Aston Martin Vantage Roadster folds its fabric roof in just 7 seconds — at speeds up to 50 km/h — transforming from a coupe to a cabriolet without missing a beat. Powered by a 4.0L twin-turbo V8 producing 503 horsepower, the Vantage delivers a visceral, analog driving experience wrapped in timeless British craftsmanship. The perfect companion for an evening drive along Al Ain\'s oasis roads.',
      features: ['7-Second Folding Roof', '4.0L Twin-Turbo V8', 'Sport+ Mode', 'Bose Audio', 'Carbon Fibre Trim', 'Limited-Slip Differential'],
      color: 'Aston Martin Racing Green',
      available: true, featured: true,
      mileageLimit: '250 km/day', deposit: 'AED 6,000 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/df140d3fe73e.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/df140d3fe73e.jpg',
        'https://sfile.chatglm.cn/images-ppt/df140d3fe73e.jpg',
        'https://sfile.chatglm.cn/images-ppt/df140d3fe73e.jpg',
      ],
    },
    // ===== NEW: 2nd Convertible =====
    {
      slug: 'bmw-m4-convertible',
      brand: bmw,
      model: 'M4 Competition Convertible',
      year: 2024,
      category: convert,
      priceDaily: 1600, priceWeekly: 9600, priceMonthly: 38000,
      engine: '3.0L Inline-6 Twin-Turbo', power: '503 HP', topSpeed: '280 km/h', acceleration: '3.9s (0-100)',
      transmission: '8-speed M Steptronic', seats: 4, fuelType: 'Petrol', drivetrain: 'RWD',
      tagline: 'The open-top M car — every drive, every season.',
      description: 'The BMW M4 Competition Convertible combines the visceral performance of the M division with the freedom of open-top driving. A 503-horsepower inline-6, M-tuned adaptive suspension, and a folding soft-top that opens in just 14 seconds. The ideal choice for those who want supercar pace with room for friends and the wind in their hair.',
      features: ['503 HP Inline-6', 'M Sport Differential', 'Adaptive M Suspension', '14-Second Folding Roof', 'Harman Kardon Audio', 'Carbon Roof (Coupe)'],
      color: 'Sao Paulo Yellow',
      available: true, featured: false,
      mileageLimit: '300 km/day', deposit: 'AED 4,000 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/ee76fb516f28.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/ee76fb516f28.jpg',
        'https://sfile.chatglm.cn/images-ppt/ee76fb516f28.jpg',
        'https://sfile.chatglm.cn/images-ppt/ee76fb516f28.jpg',
      ],
    },
    // ===== NEW: 3rd SUV for variety =====
    {
      slug: 'audi-rs-q8',
      brand: audi,
      model: 'RS Q8',
      year: 2024,
      category: suv,
      priceDaily: 1800, priceWeekly: 10800, priceMonthly: 42000,
      engine: '4.0L V8 Twin-Turbo', power: '591 HP', topSpeed: '305 km/h', acceleration: '3.8s (0-100)',
      transmission: '8-speed Tiptronic', seats: 5, fuelType: 'Petrol', drivetrain: 'AWD',
      tagline: 'The fastest SUV in Audi\'s history.',
      description: 'The Audi RS Q8 is the apex of Audi\'s SUV lineup — a 591-horsepower V8, RS-specific quattro all-wheel drive, and a 0-100 sprint of just 3.8 seconds. The Nürburgring-tuned suspension and optional carbon ceramic brakes make this the most capable performance SUV on the market. Luxury, space, and devastating pace in one package.',
      features: ['591 HP V8', 'Quattro AWD', 'RS Sport Suspension', 'Carbon Ceramic Brakes', 'Bang & Olufsen Audio', 'Virtual Cockpit Plus'],
      color: 'Nardo Grey',
      available: true, featured: false,
      mileageLimit: '300 km/day', deposit: 'AED 4,500 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/3ab0de2ecc75.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/3ab0de2ecc75.jpg',
        'https://sfile.chatglm.cn/images-ppt/3ab0de2ecc75.jpg',
        'https://sfile.chatglm.cn/images-ppt/3ab0de2ecc75.jpg',
      ],
    },

    // ============================================================
    // EVERYDAY & ECONOMY CARS — the cars people actually rent daily
    // ============================================================

    // ===== NISSAN =====
    {
      slug: 'nissan-sunny-2024',
      brand: nissan, model: 'Sunny', year: 2024, category: sedan,
      priceDaily: 120, priceWeekly: 700, priceMonthly: 2200,
      engine: '1.6L 4-cylinder', power: '118 HP', topSpeed: '180 km/h', acceleration: '11.5s (0-100)',
      transmission: 'CVT', seats: 5, fuelType: 'Petrol', drivetrain: 'FWD',
      tagline: 'The UAE\'s favourite daily driver — reliable, efficient, affordable.',
      description: 'The Nissan Sunny is the backbone of UAE car rentals — a fuel-efficient, dependable sedan that handles daily commutes and family outings with ease. Spacious interior, large trunk, and legendary reliability make this the smart choice for budget-conscious renters.',
      features: ['Fuel Efficient', 'CVT Transmission', 'Spacious Interior', 'Bluetooth', 'Reverse Camera', 'Large Trunk'],
      color: 'White Pearl',
      available: true, featured: false,
      mileageLimit: 'Unlimited km', deposit: 'AED 1,000 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/a19dedb44078.jpeg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/a19dedb44078.jpeg',
        'https://sfile.chatglm.cn/images-ppt/a19dedb44078.jpeg',
        'https://sfile.chatglm.cn/images-ppt/a19dedb44078.jpeg',
      ],
    },
    {
      slug: 'nissan-altima-2024',
      brand: nissan, model: 'Altima', year: 2024, category: sedan,
      priceDaily: 160, priceWeekly: 950, priceMonthly: 3000,
      engine: '2.5L 4-cylinder', power: '188 HP', topSpeed: '200 km/h', acceleration: '8.2s (0-100)',
      transmission: 'CVT', seats: 5, fuelType: 'Petrol', drivetrain: 'FWD',
      tagline: 'Mid-size comfort with premium features at an honest price.',
      description: 'The Nissan Altima offers mid-size sedan comfort with premium features including a 7-inch display, Apple CarPlay, and intelligent cruise control. Perfect for business travellers and families who want more space than a compact without the premium price tag.',
      features: ['Apple CarPlay', 'Intelligent Cruise Control', '7-inch Display', 'LED Headlights', 'Keyless Entry', 'Sunroof'],
      color: 'Gun Metallic',
      available: true, featured: false,
      mileageLimit: 'Unlimited km', deposit: 'AED 1,500 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/5da6ba2377e0.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/5da6ba2377e0.jpg',
        'https://sfile.chatglm.cn/images-ppt/5da6ba2377e0.jpg',
        'https://sfile.chatglm.cn/images-ppt/5da6ba2377e0.jpg',
      ],
    },
    {
      slug: 'nissan-maxima-2024',
      brand: nissan, model: 'Maxima', year: 2024, category: sedan,
      priceDaily: 220, priceWeekly: 1300, priceMonthly: 4200,
      engine: '3.5L V6', power: '300 HP', topSpeed: '210 km/h', acceleration: '6.1s (0-100)',
      transmission: 'CVT', seats: 5, fuelType: 'Petrol', drivetrain: 'FWD',
      tagline: 'The 4-door sports car — V6 power, premium cabin.',
      description: 'The Nissan Maxima is Nissan\'s flagship sedan — a 300-horsepower V6 wrapped in a sleek, sporty body with a premium interior. Bose audio, leather seats, and a panoramic roof make this the perfect step up from the Altima for those who want performance without sacrificing practicality.',
      features: ['300 HP V6', 'Bose Audio', 'Leather Seats', 'Panoramic Roof', 'Apple CarPlay', 'Paddle Shifters'],
      color: 'Pearl White',
      available: true, featured: false,
      mileageLimit: '300 km/day', deposit: 'AED 2,000 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/57b3e2086354.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/57b3e2086354.jpg',
        'https://sfile.chatglm.cn/images-ppt/57b3e2086354.jpg',
        'https://sfile.chatglm.cn/images-ppt/57b3e2086354.jpg',
      ],
    },
    {
      slug: 'nissan-patrol-2024',
      brand: nissan, model: 'Patrol', year: 2024, category: suv,
      priceDaily: 450, priceWeekly: 2700, priceMonthly: 9500,
      engine: '5.6L V8', power: '400 HP', topSpeed: '220 km/h', acceleration: '6.6s (0-100)',
      transmission: '7-speed Auto', seats: 7, fuelType: 'Petrol', drivetrain: '4WD',
      tagline: 'The desert legend — V8 power, 7 seats, goes anywhere.',
      description: 'The Nissan Patrol is an icon of the UAE — a 5.6L V8-powered 4x4 that conquers dunes and city streets with equal authority. 7 seats, premium leather interior, and legendary off-road capability make this the go-to SUV for families and adventure seekers alike.',
      features: ['400 HP V8', '7 Seats', '4WD Off-Road', 'Leather Interior', 'Bose Audio', 'Desert Mode'],
      color: 'Desert Beige',
      available: true, featured: true,
      mileageLimit: '300 km/day', deposit: 'AED 3,000 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/d15210b9e2ef.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/d15210b9e2ef.jpg',
        'https://sfile.chatglm.cn/images-ppt/d15210b9e2ef.jpg',
        'https://sfile.chatglm.cn/images-ppt/d15210b9e2ef.jpg',
      ],
    },
    {
      slug: 'nissan-kicks-2024',
      brand: nissan, model: 'Kicks', year: 2024, category: compact,
      priceDaily: 130, priceWeekly: 780, priceMonthly: 2500,
      engine: '1.6L 4-cylinder', power: '122 HP', topSpeed: '175 km/h', acceleration: '10.5s (0-100)',
      transmission: 'CVT', seats: 5, fuelType: 'Petrol', drivetrain: 'FWD',
      tagline: 'Stylish compact crossover — perfect for city adventures.',
      description: 'The Nissan Kicks is a stylish, fuel-efficient compact crossover ideal for navigating Al Ain\'s streets. With its bold design, nimble handling, and modern tech including Apple CarPlay and Android Auto, the Kicks delivers big-city style in a park-anywhere package.',
      features: ['Apple CarPlay', 'Android Auto', 'Around View Camera', 'Compact Size', 'Fuel Efficient', 'Bose Audio'],
      color: 'Brass Metallic',
      available: true, featured: false,
      mileageLimit: 'Unlimited km', deposit: 'AED 1,200 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/309d6afa2d99.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/309d6afa2d99.jpg',
        'https://sfile.chatglm.cn/images-ppt/309d6afa2d99.jpg',
        'https://sfile.chatglm.cn/images-ppt/309d6afa2d99.jpg',
      ],
    },
    {
      slug: 'nissan-pathfinder-2024',
      brand: nissan, model: 'Pathfinder', year: 2024, category: suv,
      priceDaily: 300, priceWeekly: 1800, priceMonthly: 6000,
      engine: '3.5L V6', power: '284 HP', topSpeed: '200 km/h', acceleration: '7.3s (0-100)',
      transmission: '9-speed Auto', seats: 7, fuelType: 'Petrol', drivetrain: 'AWD',
      tagline: '7-seat family SUV with V6 power and all-wheel drive.',
      description: 'The Nissan Pathfinder is the ultimate family SUV — 7 seats, a 3.5L V6, and intelligent all-wheel drive. Whether it\'s the school run or a weekend desert camping trip, the Pathfinder handles it all with comfort, space, and capability.',
      features: ['7 Seats', 'AWD', '9-speed Auto', 'Panoramic Roof', 'Tri-Zone Climate', 'Smart Around View'],
      color: 'Diamond Black',
      available: true, featured: false,
      mileageLimit: '300 km/day', deposit: 'AED 2,500 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/ef44e9c98a65.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/ef44e9c98a65.jpg',
        'https://sfile.chatglm.cn/images-ppt/ef44e9c98a65.jpg',
        'https://sfile.chatglm.cn/images-ppt/ef44e9c98a65.jpg',
      ],
    },

    // ===== HONDA =====
    {
      slug: 'honda-civic-2024',
      brand: honda, model: 'Civic', year: 2024, category: sedan,
      priceDaily: 140, priceWeekly: 840, priceMonthly: 2700,
      engine: '1.5L Turbo', power: '180 HP', topSpeed: '200 km/h', acceleration: '7.8s (0-100)',
      transmission: 'CVT', seats: 5, fuelType: 'Petrol', drivetrain: 'FWD',
      tagline: 'Sporty, efficient, and endlessly reliable.',
      description: 'The Honda Civic is the benchmark for compact sedans — a 1.5L turbocharged engine delivering 180 HP, sporty handling, and Honda\'s legendary reliability. With Apple CarPlay, Honda Sensing safety suite, and a sleek new design, the Civic is perfect for daily commutes and weekend trips.',
      features: ['1.5L Turbo', 'Honda Sensing Safety', 'Apple CarPlay', 'LED Headlights', 'Sport Mode', 'Fuel Efficient'],
      color: 'Rallye Red',
      available: true, featured: true,
      mileageLimit: 'Unlimited km', deposit: 'AED 1,200 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/a6eed4acb9d1.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/a6eed4acb9d1.jpg',
        'https://sfile.chatglm.cn/images-ppt/a6eed4acb9d1.jpg',
        'https://sfile.chatglm.cn/images-ppt/a6eed4acb9d1.jpg',
      ],
    },
    {
      slug: 'honda-accord-2024',
      brand: honda, model: 'Accord', year: 2024, category: sedan,
      priceDaily: 180, priceWeekly: 1080, priceMonthly: 3500,
      engine: '1.5L Turbo', power: '192 HP', topSpeed: '210 km/h', acceleration: '7.4s (0-100)',
      transmission: 'CVT', seats: 5, fuelType: 'Petrol', drivetrain: 'FWD',
      tagline: 'Mid-size refinement with Honda reliability.',
      description: 'The Honda Accord is the gold standard of mid-size sedans — refined, spacious, and powered by a 192-HP turbocharged engine. With premium interior materials, an 8-inch display, and Honda Sensing safety features, the Accord delivers near-luxury experience at a practical price.',
      features: ['192 HP Turbo', 'Honda Sensing', '8-inch Display', 'Wireless CarPlay', 'Heated Seats', 'Sunroof'],
      color: 'Modern Steel',
      available: true, featured: false,
      mileageLimit: 'Unlimited km', deposit: 'AED 1,500 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/0413fb1f90f3.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/0413fb1f90f3.jpg',
        'https://sfile.chatglm.cn/images-ppt/0413fb1f90f3.jpg',
        'https://sfile.chatglm.cn/images-ppt/0413fb1f90f3.jpg',
      ],
    },
    {
      slug: 'honda-city-2024',
      brand: honda, model: 'City', year: 2024, category: compact,
      priceDaily: 110, priceWeekly: 660, priceMonthly: 2100,
      engine: '1.5L 4-cylinder', power: '121 HP', topSpeed: '185 km/h', acceleration: '10.2s (0-100)',
      transmission: 'CVT', seats: 5, fuelType: 'Petrol', drivetrain: 'FWD',
      tagline: 'Compact, efficient, and packed with features.',
      description: 'The Honda City is a compact sedan built for efficiency and practicality. With its 1.5L engine, class-leading fuel economy, and Honda Sensing safety suite, the City is perfect for daily commuters and small families who want Honda reliability in a smaller, more affordable package.',
      features: ['Honda Sensing', 'Fuel Efficient', '8-inch Display', 'Apple CarPlay', 'Reverse Camera', 'Compact Size'],
      color: 'Platinum White',
      available: true, featured: false,
      mileageLimit: 'Unlimited km', deposit: 'AED 1,000 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/77c79c26caf4.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/77c79c26caf4.jpg',
        'https://sfile.chatglm.cn/images-ppt/77c79c26caf4.jpg',
        'https://sfile.chatglm.cn/images-ppt/77c79c26caf4.jpg',
      ],
    },

    // ===== TOYOTA =====
    {
      slug: 'toyota-camry-2024',
      brand: toyota, model: 'Camry', year: 2024, category: sedan,
      priceDaily: 150, priceWeekly: 900, priceMonthly: 2900,
      engine: '2.5L 4-cylinder', power: '203 HP', topSpeed: '210 km/h', acceleration: '8.0s (0-100)',
      transmission: '8-speed Auto', seats: 5, fuelType: 'Petrol', drivetrain: 'FWD',
      tagline: 'The best-selling sedan in the UAE — bulletproof reliability.',
      description: 'The Toyota Camry is the UAE\'s best-selling sedan — and for good reason. A refined 2.5L engine, 8-speed automatic, and Toyota\'s legendary reliability make the Camry the default choice for daily drivers, business travellers, and families. Comfortable, efficient, and built to last.',
      features: ['8-speed Auto', 'Toyota Safety Sense', 'Apple CarPlay', 'LED Headlights', 'Dual Zone Climate', 'Premium Audio'],
      color: 'Pearl White',
      available: true, featured: true,
      mileageLimit: 'Unlimited km', deposit: 'AED 1,200 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/1bb464967029.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/1bb464967029.jpg',
        'https://sfile.chatglm.cn/images-ppt/1bb464967029.jpg',
        'https://sfile.chatglm.cn/images-ppt/1bb464967029.jpg',
      ],
    },
    {
      slug: 'toyota-corolla-2024',
      brand: toyota, model: 'Corolla', year: 2024, category: compact,
      priceDaily: 100, priceWeekly: 600, priceMonthly: 1900,
      engine: '1.6L 4-cylinder', power: '121 HP', topSpeed: '180 km/h', acceleration: '10.8s (0-100)',
      transmission: 'CVT', seats: 5, fuelType: 'Petrol', drivetrain: 'FWD',
      tagline: 'The world\'s best-selling car — unbeatable value.',
      description: 'The Toyota Corolla needs no introduction — it\'s the world\'s best-selling car. Efficient, reliable, and affordable, the Corolla is the smart choice for budget-conscious renters who want Toyota quality without the premium price. Perfect for daily commutes, errands, and city driving.',
      features: ['Toyota Safety Sense', 'Fuel Efficient', 'Apple CarPlay', 'LED Headlights', 'CVT', 'Compact Size'],
      color: 'Celestial Silver',
      available: true, featured: false,
      mileageLimit: 'Unlimited km', deposit: 'AED 900 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/d117716ba0d3.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/d117716ba0d3.jpg',
        'https://sfile.chatglm.cn/images-ppt/d117716ba0d3.jpg',
        'https://sfile.chatglm.cn/images-ppt/d117716ba0d3.jpg',
      ],
    },
    {
      slug: 'toyota-land-cruiser-2024',
      brand: toyota, model: 'Land Cruiser', year: 2024, category: suv,
      priceDaily: 500, priceWeekly: 3000, priceMonthly: 11000,
      engine: '3.5L Twin-Turbo V6', power: '409 HP', topSpeed: '230 km/h', acceleration: '6.3s (0-100)',
      transmission: '10-speed Auto', seats: 7, fuelType: 'Petrol', drivetrain: '4WD',
      tagline: 'The unstoppable desert king — V6 twin-turbo, 7 seats.',
      description: 'The Toyota Land Cruiser is the UAE\'s most trusted SUV — a 3.5L twin-turbo V6 producing 409 HP, legendary off-road capability, and 7 seats of luxury. From dune bashing to school runs, the Land Cruiser does it all. The default choice for those who need serious capability without compromise.',
      features: ['409 HP Twin-Turbo V6', '7 Seats', '4WD Off-Road', 'Crawl Control', 'Leather Interior', 'JBL Audio'],
      color: 'Pearl White',
      available: true, featured: true,
      mileageLimit: '300 km/day', deposit: 'AED 3,500 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/c0e6c56bd122.png',
      images: [
        'https://sfile.chatglm.cn/images-ppt/c0e6c56bd122.png',
        'https://sfile.chatglm.cn/images-ppt/c0e6c56bd122.png',
        'https://sfile.chatglm.cn/images-ppt/c0e6c56bd122.png',
      ],
    },
    {
      slug: 'toyota-hilux-2024',
      brand: toyota, model: 'Hilux', year: 2024, category: suv,
      priceDaily: 280, priceWeekly: 1680, priceMonthly: 5500,
      engine: '2.7L 4-cylinder', power: '164 HP', topSpeed: '185 km/h', acceleration: '11.5s (0-100)',
      transmission: '6-speed Auto', seats: 5, fuelType: 'Petrol', drivetrain: '4WD',
      tagline: 'Unbreakable workhorse — for work sites and desert adventures.',
      description: 'The Toyota Hilux is famous worldwide for being virtually indestructible. A 2.7L engine, 4WD capability, and a durable bed make this the perfect truck for construction sites, desert camping, or any job that demands a vehicle that can take abuse and keep going.',
      features: ['4WD', 'Durable Bed', 'Towing Capacity', 'High Ground Clearance', '6-speed Auto', 'Apple CarPlay'],
      color: 'Havana Brown',
      available: true, featured: false,
      mileageLimit: '300 km/day', deposit: 'AED 2,000 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/de6f3a6adfa5.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/de6f3a6adfa5.jpg',
        'https://sfile.chatglm.cn/images-ppt/de6f3a6adfa5.jpg',
        'https://sfile.chatglm.cn/images-ppt/de6f3a6adfa5.jpg',
      ],
    },

    // ===== HYUNDAI =====
    {
      slug: 'hyundai-elantra-2024',
      brand: hyundai, model: 'Elantra', year: 2024, category: compact,
      priceDaily: 100, priceWeekly: 600, priceMonthly: 1900,
      engine: '1.6L 4-cylinder', power: '123 HP', topSpeed: '185 km/h', acceleration: '10.5s (0-100)',
      transmission: 'CVT', seats: 5, fuelType: 'Petrol', drivetrain: 'FWD',
      tagline: 'Sharp design, smart tech, unbeatable value.',
      description: 'The Hyundai Elantra turned heads with its bold, parametric design. Under the skin, it\'s a practical, fuel-efficient compact sedan with a 1.6L engine, 8-inch display, and Apple CarPlay. Perfect for renters who want style and value in equal measure.',
      features: ['Apple CarPlay', '8-inch Display', 'Fuel Efficient', 'Smart Cruise Control', 'LED DRLs', 'Wireless Charging'],
      color: 'Intense Blue',
      available: true, featured: false,
      mileageLimit: 'Unlimited km', deposit: 'AED 900 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/43d4d0a4b52f.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/43d4d0a4b52f.jpg',
        'https://sfile.chatglm.cn/images-ppt/43d4d0a4b52f.jpg',
        'https://sfile.chatglm.cn/images-ppt/43d4d0a4b52f.jpg',
      ],
    },
    {
      slug: 'hyundai-sonata-2024',
      brand: hyundai, model: 'Sonata', year: 2024, category: sedan,
      priceDaily: 140, priceWeekly: 840, priceMonthly: 2700,
      engine: '2.5L 4-cylinder', power: '191 HP', topSpeed: '205 km/h', acceleration: '8.0s (0-100)',
      transmission: '8-speed Auto', seats: 5, fuelType: 'Petrol', drivetrain: 'FWD',
      tagline: 'Sleek mid-size sedan with premium features.',
      description: 'The Hyundai Sonata is a striking mid-size sedan with a 2.5L engine, 191 HP, and a premium interior. With a 10.25-inch display, wireless Apple CarPlay, and Hyundai SmartSense safety suite, the Sonata offers near-luxury features at a mainstream price.',
      features: ['191 HP', '10.25-inch Display', 'Wireless CarPlay', 'SmartSense Safety', 'Sunroof', 'LED Headlights'],
      color: 'Phantom Black',
      available: true, featured: false,
      mileageLimit: 'Unlimited km', deposit: 'AED 1,200 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/0cd7e3db9da3.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/0cd7e3db9da3.jpg',
        'https://sfile.chatglm.cn/images-ppt/0cd7e3db9da3.jpg',
        'https://sfile.chatglm.cn/images-ppt/0cd7e3db9da3.jpg',
      ],
    },
    {
      slug: 'hyundai-tucson-2024',
      brand: hyundai, model: 'Tucson', year: 2024, category: suv,
      priceDaily: 200, priceWeekly: 1200, priceMonthly: 4000,
      engine: '2.5L 4-cylinder', power: '187 HP', topSpeed: '195 km/h', acceleration: '8.8s (0-100)',
      transmission: '8-speed Auto', seats: 5, fuelType: 'Petrol', drivetrain: 'AWD',
      tagline: 'Bold crossover SUV with modern design and AWD.',
      description: 'The Hyundai Tucson is a bold, modern crossover SUV with 187 HP, all-wheel drive, and a tech-forward interior. 10.25-inch display, wireless charging, and Hyundai SmartSense safety suite make the Tucson the perfect family SUV for those who want style and practicality.',
      features: ['187 HP', 'AWD', '10.25-inch Display', 'SmartSense Safety', 'Panoramic Roof', 'Wireless Charging'],
      color: 'Shimmering Silver',
      available: true, featured: false,
      mileageLimit: 'Unlimited km', deposit: 'AED 1,500 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/d7990576cdd0.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/d7990576cdd0.jpg',
        'https://sfile.chatglm.cn/images-ppt/d7990576cdd0.jpg',
        'https://sfile.chatglm.cn/images-ppt/d7990576cdd0.jpg',
      ],
    },

    // ===== CHEVROLET =====
    {
      slug: 'chevrolet-tahoe-2024',
      brand: chevrolet, model: 'Tahoe', year: 2024, category: suv,
      priceDaily: 350, priceWeekly: 2100, priceMonthly: 7500,
      engine: '5.3L V8', power: '355 HP', topSpeed: '200 km/h', acceleration: '7.2s (0-100)',
      transmission: '10-speed Auto', seats: 7, fuelType: 'Petrol', drivetrain: '4WD',
      tagline: 'Full-size American V8 SUV — 7 seats, serious towing.',
      description: 'The Chevrolet Tahoe is a full-size American SUV with a 5.3L V8, 7 seats, and 4WD capability. Perfect for large families or those who need serious towing capacity. Magnetic Ride Control, Bose audio, and a 10.2-inch touchscreen make every journey comfortable.',
      features: ['5.3L V8', '7 Seats', '4WD', 'Magnetic Ride Control', 'Bose Audio', '10.2-inch Touchscreen'],
      color: 'Summit White',
      available: true, featured: false,
      mileageLimit: '300 km/day', deposit: 'AED 2,500 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/5fc89b7c66c6.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/5fc89b7c66c6.jpg',
        'https://sfile.chatglm.cn/images-ppt/5fc89b7c66c6.jpg',
        'https://sfile.chatglm.cn/images-ppt/5fc89b7c66c6.jpg',
      ],
    },
    {
      slug: 'chevrolet-malibu-2024',
      brand: chevrolet, model: 'Malibu', year: 2024, category: sedan,
      priceDaily: 130, priceWeekly: 780, priceMonthly: 2500,
      engine: '1.5L Turbo', power: '160 HP', topSpeed: '195 km/h', acceleration: '9.1s (0-100)',
      transmission: 'CVT', seats: 5, fuelType: 'Petrol', drivetrain: 'FWD',
      tagline: 'Comfortable mid-size sedan with turbo power.',
      description: 'The Chevrolet Malibu is a comfortable mid-size sedan with a 1.5L turbocharged engine, 160 HP, and a smooth CVT. With an 8-inch display, Apple CarPlay, and a spacious interior, the Malibu is a great value option for daily commuters and small families.',
      features: ['1.5L Turbo', 'Apple CarPlay', '8-inch Display', 'Heated Seats', 'Dual Zone Climate', 'Fuel Efficient'],
      color: 'Mosaic Black',
      available: true, featured: false,
      mileageLimit: 'Unlimited km', deposit: 'AED 1,100 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/bfdcc71bf310.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/bfdcc71bf310.jpg',
        'https://sfile.chatglm.cn/images-ppt/bfdcc71bf310.jpg',
        'https://sfile.chatglm.cn/images-ppt/bfdcc71bf310.jpg',
      ],
    },
    {
      slug: 'chevrolet-spark-2024',
      brand: chevrolet, model: 'Spark', year: 2024, category: compact,
      priceDaily: 80, priceWeekly: 480, priceMonthly: 1500,
      engine: '1.4L 4-cylinder', power: '98 HP', topSpeed: '170 km/h', acceleration: '12.5s (0-100)',
      transmission: 'CVT', seats: 4, fuelType: 'Petrol', drivetrain: 'FWD',
      tagline: 'Ultra-compact, ultra-affordable, ultra-efficient.',
      description: 'The Chevrolet Spark is the most affordable car in our fleet — a tiny, efficient hatchback perfect for city driving, parking in tight spots, and saving on fuel. Don\'t let the size fool you: the Spark has Apple CarPlay, a 7-inch display, and enough room for 4 people. The budget champion.',
      features: ['Apple CarPlay', '7-inch Display', 'Ultra Fuel Efficient', 'Easy Parking', 'CVT', 'Compact Size'],
      color: 'Nitro Yellow',
      available: true, featured: false,
      mileageLimit: 'Unlimited km', deposit: 'AED 700 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/b924ca736658.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/b924ca736658.jpg',
        'https://sfile.chatglm.cn/images-ppt/b924ca736658.jpg',
        'https://sfile.chatglm.cn/images-ppt/b924ca736658.jpg',
      ],
    },

    // ===== MITSUBISHI =====
    {
      slug: 'mitsubishi-lancer-2024',
      brand: mitsubishi, model: 'Lancer EX', year: 2024, category: sedan,
      priceDaily: 90, priceWeekly: 540, priceMonthly: 1700,
      engine: '1.6L 4-cylinder', power: '117 HP', topSpeed: '180 km/h', acceleration: '11.0s (0-100)',
      transmission: 'CVT', seats: 5, fuelType: 'Petrol', drivetrain: 'FWD',
      tagline: 'Reliable, efficient, and remarkably affordable.',
      description: 'The Mitsubishi Lancer EX is a dependable, fuel-efficient sedan that\'s been a staple of UAE rental fleets for years. Simple, reliable, and affordable to maintain — the Lancer is the no-nonsense choice for renters who need basic transportation that just works.',
      features: ['Fuel Efficient', 'CVT', 'Bluetooth', 'Reverse Camera', 'Spacious Trunk', 'Reliable'],
      color: 'Cool Silver',
      available: true, featured: false,
      mileageLimit: 'Unlimited km', deposit: 'AED 800 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/a1bad9105cce.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/a1bad9105cce.jpg',
        'https://sfile.chatglm.cn/images-ppt/a1bad9105cce.jpg',
        'https://sfile.chatglm.cn/images-ppt/a1bad9105cce.jpg',
      ],
    },
    {
      slug: 'mitsubishi-pajero-2024',
      brand: mitsubishi, model: 'Pajero', year: 2024, category: suv,
      priceDaily: 300, priceWeekly: 1800, priceMonthly: 6000,
      engine: '3.8L V6', power: '218 HP', topSpeed: '200 km/h', acceleration: '9.5s (0-100)',
      transmission: '5-speed Auto', seats: 7, fuelType: 'Petrol', drivetrain: '4WD',
      tagline: 'Legendary off-road SUV with 7 seats and V6 power.',
      description: 'The Mitsubishi Pajero is a legendary off-road SUV with a 3.8L V6, 7 seats, and genuine 4WD capability. Known for its durability and desert-conquering ability, the Pajero is the trusted choice for families who need an SUV that can handle both daily life and weekend adventures.',
      features: ['3.8L V6', '7 Seats', '4WD Off-Road', 'Rear Differential Lock', 'Leather Seats', 'Rockford Audio'],
      color: 'Warm White',
      available: true, featured: false,
      mileageLimit: '300 km/day', deposit: 'AED 2,200 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/2d7e1a08bcab.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/2d7e1a08bcab.jpg',
        'https://sfile.chatglm.cn/images-ppt/2d7e1a08bcab.jpg',
        'https://sfile.chatglm.cn/images-ppt/2d7e1a08bcab.jpg',
      ],
    },
    {
      slug: 'mitsubishi-asx-2024',
      brand: mitsubishi, model: 'ASX', year: 2024, category: compact,
      priceDaily: 110, priceWeekly: 660, priceMonthly: 2100,
      engine: '2.0L 4-cylinder', power: '148 HP', topSpeed: '185 km/h', acceleration: '10.2s (0-100)',
      transmission: 'CVT', seats: 5, fuelType: 'Petrol', drivetrain: 'FWD',
      tagline: 'Compact crossover with SUV attitude.',
      description: 'The Mitsubishi ASX is a compact crossover that combines SUV styling with hatchback practicality. 148 HP, 2.0L engine, and a comfortable ride make the ASX perfect for small families who want a higher driving position without the fuel costs of a full SUV.',
      features: ['148 HP', 'Compact Crossover', 'Apple CarPlay', 'Reverse Camera', 'High Driving Position', 'Fuel Efficient'],
      color: 'Red Diamond',
      available: true, featured: false,
      mileageLimit: 'Unlimited km', deposit: 'AED 1,000 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/a179880b7a37.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/a179880b7a37.jpg',
        'https://sfile.chatglm.cn/images-ppt/a179880b7a37.jpg',
        'https://sfile.chatglm.cn/images-ppt/a179880b7a37.jpg',
      ],
    },

    // ===== KIA =====
    {
      slug: 'kia-picanto-2024',
      brand: kia, model: 'Picanto', year: 2024, category: compact,
      priceDaily: 70, priceWeekly: 420, priceMonthly: 1300,
      engine: '1.0L 3-cylinder', power: '66 HP', topSpeed: '160 km/h', acceleration: '14.0s (0-100)',
      transmission: '5-speed Manual', seats: 4, fuelType: 'Petrol', drivetrain: 'FWD',
      tagline: 'The city car — park anywhere, sip fuel.',
      description: 'The Kia Picanto is the ultimate city car — tiny, incredibly fuel-efficient, and easy to park in the tightest spots. Perfect for renters on a budget who mainly need a car for short city trips. Apple CarPlay, reverse camera, and a surprising amount of interior space for its size.',
      features: ['Ultra Fuel Efficient', 'Easy Parking', 'Apple CarPlay', 'Reverse Camera', 'Compact Size', 'Budget Friendly'],
      color: 'Clear White',
      available: true, featured: false,
      mileageLimit: 'Unlimited km', deposit: 'AED 600 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/c24fc1f5e963.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/c24fc1f5e963.jpg',
        'https://sfile.chatglm.cn/images-ppt/c24fc1f5e963.jpg',
        'https://sfile.chatglm.cn/images-ppt/c24fc1f5e963.jpg',
      ],
    },
    {
      slug: 'kia-sportage-2024',
      brand: kia, model: 'Sportage', year: 2024, category: suv,
      priceDaily: 190, priceWeekly: 1140, priceMonthly: 3800,
      engine: '2.5L 4-cylinder', power: '187 HP', topSpeed: '195 km/h', acceleration: '8.7s (0-100)',
      transmission: '8-speed Auto', seats: 5, fuelType: 'Petrol', drivetrain: 'AWD',
      tagline: 'Award-winning crossover with bold design and AWD.',
      description: 'The Kia Sportage is an award-winning crossover SUV with a bold new design, 187 HP, and all-wheel drive. A 12.3-inch display, panoramic roof, and premium interior make the Sportage one of the best-value family SUVs on the market. Smart choice for families who want premium features without the premium price.',
      features: ['187 HP', 'AWD', '12.3-inch Display', 'Panoramic Roof', 'Bose Audio', 'Smart Cruise Control'],
      color: 'Snow White Pearl',
      available: true, featured: false,
      mileageLimit: 'Unlimited km', deposit: 'AED 1,500 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/726a61f4a7a8.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/726a61f4a7a8.jpg',
        'https://sfile.chatglm.cn/images-ppt/726a61f4a7a8.jpg',
        'https://sfile.chatglm.cn/images-ppt/726a61f4a7a8.jpg',
      ],
    },

    // ===== MERCEDES-BENZ (mainstream models) =====
    {
      slug: 'mercedes-c-class-2024',
      brand: mercedesB, model: 'C-Class', year: 2024, category: luxury,
      priceDaily: 350, priceWeekly: 2100, priceMonthly: 7500,
      engine: '1.5L Turbo + Electric', power: '204 HP', topSpeed: '240 km/h', acceleration: '7.3s (0-100)',
      transmission: '9-speed Auto', seats: 5, fuelType: 'Hybrid', drivetrain: 'RWD',
      tagline: 'Entry-level luxury done right — the Mercedes benchmark.',
      description: 'The Mercedes-Benz C-Class is the entry point into the Mercedes world — a 1.5L turbo hybrid with 204 HP, a 11.9-inch touchscreen, and the premium cabin feel Mercedes is famous for. The perfect choice for business travellers who want luxury without the S-Class price tag.',
      features: ['1.5L Turbo Hybrid', '11.9-inch Touchscreen', 'Burmester Audio', 'MBUX Voice Control', 'Ambient Lighting', 'Heated Seats'],
      color: 'Obsidian Black',
      available: true, featured: true,
      mileageLimit: '300 km/day', deposit: 'AED 2,500 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/34d58093a4b7.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/34d58093a4b7.jpg',
        'https://sfile.chatglm.cn/images-ppt/34d58093a4b7.jpg',
        'https://sfile.chatglm.cn/images-ppt/34d58093a4b7.jpg',
      ],
    },
    {
      slug: 'mercedes-e-class-2024',
      brand: mercedesB, model: 'E-Class', year: 2024, category: luxury,
      priceDaily: 450, priceWeekly: 2700, priceMonthly: 9500,
      engine: '2.0L Turbo + Electric', power: '258 HP', topSpeed: '250 km/h', acceleration: '6.2s (0-100)',
      transmission: '9-speed Auto', seats: 5, fuelType: 'Hybrid', drivetrain: 'RWD',
      tagline: 'The executive sedan — refined, powerful, unmistakably Mercedes.',
      description: 'The Mercedes-Benz E-Class is the benchmark executive sedan — a 2.0L turbo hybrid with 258 HP, a 12.3-inch digital cockpit, and unparalleled ride comfort. Whether it\'s a business trip or a weekend getaway, the E-Class delivers the refined, effortless experience that has defined Mercedes for decades.',
      features: ['258 HP Hybrid', '12.3-inch Cockpit', 'Burmester 4D Audio', 'Air Suspension', 'MBUX Superscreen', 'Driver Assistance Package'],
      color: 'Selenite Grey',
      available: true, featured: false,
      mileageLimit: '300 km/day', deposit: 'AED 3,000 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/b91d96129713.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/b91d96129713.jpg',
        'https://sfile.chatglm.cn/images-ppt/b91d96129713.jpg',
        'https://sfile.chatglm.cn/images-ppt/b91d96129713.jpg',
      ],
    },
    {
      slug: 'mercedes-gle-2024',
      brand: mercedesB, model: 'GLE', year: 2024, category: suv,
      priceDaily: 550, priceWeekly: 3300, priceMonthly: 12000,
      engine: '3.0L Inline-6 Turbo + Electric', power: '367 HP', topSpeed: '245 km/h', acceleration: '5.7s (0-100)',
      transmission: '9-speed Auto', seats: 5, fuelType: 'Hybrid', drivetrain: 'AWD',
      tagline: 'Luxury SUV with inline-6 power and AWD.',
      description: 'The Mercedes-Benz GLE is a luxury SUV that combines a 3.0L inline-6 hybrid with 367 HP and 4MATIC all-wheel drive. Air suspension, a 12.3-inch MBUX infotainment system, and a panoramic roof make the GLE the ultimate family luxury SUV. Perfect for those who want S-Class comfort in an SUV body.',
      features: ['367 HP Inline-6 Hybrid', '4MATIC AWD', 'Air Suspension', '12.3-inch MBUX', 'Burmester Audio', 'Panoramic Roof'],
      color: 'Iridium Silver',
      available: true, featured: false,
      mileageLimit: '300 km/day', deposit: 'AED 3,500 refundable',
      heroImage: 'https://sfile.chatglm.cn/images-ppt/eb54d6ed9013.jpg',
      images: [
        'https://sfile.chatglm.cn/images-ppt/eb54d6ed9013.jpg',
        'https://sfile.chatglm.cn/images-ppt/eb54d6ed9013.jpg',
        'https://sfile.chatglm.cn/images-ppt/eb54d6ed9013.jpg',
      ],
    },
  ];

  for (const c of cars) {
    const car = await db.car.create({
      data: {
        slug: c.slug,
        brandId: c.brand.id,
        model: c.model,
        year: c.year,
        categoryId: c.category.id,
        priceDaily: c.priceDaily,
        priceWeekly: c.priceWeekly,
        priceMonthly: c.priceMonthly,
        engine: c.engine,
        power: c.power,
        topSpeed: c.topSpeed,
        acceleration: c.acceleration,
        transmission: c.transmission,
        seats: c.seats,
        fuelType: c.fuelType,
        drivetrain: c.drivetrain,
        tagline: c.tagline,
        description: c.description,
        features: JSON.stringify(c.features),
        color: c.color,
        available: c.available,
        featured: c.featured,
        mileageLimit: c.mileageLimit,
        deposit: c.deposit,
        heroImage: c.heroImage,
        images: { create: c.images.map((url, i) => ({ url, order: i, caption: `${c.model} view ${i+1}` })) },
      },
    });
    console.log(`  ✓ ${c.brand.name} ${c.model} (${car.id})`);
  }

  // ---------- Site Settings ----------
  await db.siteSettings.create({
    data: {
      brandName: 'PHRONESIS',
      tagline: 'Luxury Car Atelier — Al Ain',
      phone: '+971561669766',
      whatsapp: '+971561669766',
      email: 'concierge@phronesis.ae',
      address: 'Sheikh Zayed Bin Sultan Street, Al Ain, UAE',
      instagram: 'https://instagram.com',
      adminPassword: 'phronesis2024',
      heroHeadline: 'The Art of Arrival',
      heroSubtext: "Al Ain's atelier of extraordinary automobiles — curated for those who understand that how you arrive matters.",
      aboutText: "Phronesis — from the Greek for practical wisdom — was founded on a simple premise: that the experience of renting an extraordinary automobile should be as refined as the automobile itself. From our atelier in the Garden City of Al Ain, we serve a discerning clientele across the UAE who understand that true luxury is not about logos or price tags, but about the quality of attention, the seamlessness of service, and the calibre of the machines we curate. Every car in our collection is hand-selected, manufacturer-maintained, and delivered with concierge care — 24 hours a day, seven days a week — to Al Ain, Abu Dhabi, Dubai, and beyond.",
    },
  });

  console.log('✅ Seed complete.');
  console.log('   Admin login: /#/admin  |  password: phronesis2024');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await db.$disconnect(); });
